// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1GIBECMfeHPAIRDuQ-1865QhwVNayW0s',
    appId: '1:686602636387:web:d13f8fb1c86873961d7c56',
    messagingSenderId: '686602636387',
    projectId: 'stockconsole-e8d10',
    authDomain: 'stockconsole-e8d10.firebaseapp.com',
    storageBucket: 'stockconsole-e8d10.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfuJBj0ZY9RuCkUhFHtHVvoTK3UBtzQ_8',
    appId: '1:686602636387:android:68c2f525a59731171d7c56',
    messagingSenderId: '686602636387',
    projectId: 'stockconsole-e8d10',
    storageBucket: 'stockconsole-e8d10.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD27sTLsA3tyOYJhRkFiV2Qb0SVjKkYRIg',
    appId: '1:686602636387:ios:80025f92387f0ae31d7c56',
    messagingSenderId: '686602636387',
    projectId: 'stockconsole-e8d10',
    storageBucket: 'stockconsole-e8d10.appspot.com',
    androidClientId: '686602636387-0n8d3go90eh8pqi77a121j9eevfj3j02.apps.googleusercontent.com',
    iosClientId: '686602636387-t4m5964h2ol7evbh00715bboifnnc954.apps.googleusercontent.com',
    iosBundleId: 'com.example.stockconsole',
  );
}
